version: "3"
services:
  web:
    container_name: todo_web
    volumes: 
      - ./todo_web:/todo_web/
    build:
      dockerfile: "Dockerfile"
      context: "./todo_web"
    expose:
      - 3000
  app:
    build:
      dockerfile: "Dockerfile"
      context: "./todo"
    container_name: app
    volumes: 
      - ./todo:/todo
    ports:
      - '3001:3000'
    working_dir:
      '/app'
    entrypoint:
      'rails s -b 0.0.0.0'
  db:
    image: "postgres:9.5.8"
  server:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    build:
      dockerfile: "Dockerfile"
      context: "./nginx"
    ports:
      - "81:80"
